version: '3.9'
services:

  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping
    ports:
      - '5432:5432'
    command: [ "postgres", "-c", "wal_level=logical"]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
  #    ports:
  #      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:6.2.1 #debezium/kafka:1.9.4.Final
    depends_on:
      - zookeeper
    ports:
      - 29095:29095
      - 9095:9095
      - 9092:9092
    environment:
      ALLOW_PLAINTEXT_LISTENERS: yes
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9095,PLAINTEXT_HOST://localhost:29095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL,SSL_HOST:SSL
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9095,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9095,PLAINTEXT_HOST://localhost:9092

  connect:
    image: debezium/connect:1.9.4.Final
    depends_on:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9095
      - GROUP_ID=shopping-connect
      - CONFIG_STORAGE_TOPIC=debezium_connect_config
      - OFFSET_STORAGE_TOPIC=debezium_connect_offsets
      - STATUS_STORAGE_TOPIC=debezium_connect_status

  shopping:
    image: kovalev-shopping:0.0.1-SNAPSHOT
    depends_on:
      - kafka
      - postgres
      - connect
    environment:
      - SHOPPING_DB_URL=jdbc:postgresql://postgres:5432/shopping
      - SHOPPING_CART_EXPIRATION_ROUTINEDELAY=2m
      - SHOPPING_CART_EXPIRATION_TTL=3m
      - SERVER_PORT=8088
    ports:
      - 8080:8088